config/routes.rb
SampleApp::Application.routes.draw do

  get "score/index"

  resources :users, :hurdles, :wattballs, :teams, :matches, :tickets, :scores, :heats
  match '/tickets/send_mail', to: 'tickets#send_mail'
  resources :sessions, only: [:new, :create, :destroy]
  

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/help',    to: "static_pages#help"
  match '/about',   to:"static_pages#about"
  match '/contact', to: "static_pages#contact"
  match '/direction', to: "static_pages#direction"
  
  match '/participants', to: "static_pages#participants"
  match '/participants/athletes', to: "hurdles#index"
  match '/participants/teams', to: "teams#index"
  
  match '/schedules', to: "static_pages#schedules"
  match '/schedules/matches', to: "matches#index"
  match '/schedules/heats', to: "heats#index"
  match '/topscorers', to: "scores#index"

  
  root to: 'static_pages#home'
  
  namespace :admin do
    resources :staffs
    resources :staff_sessions, only: [:new, :create, :destroy]
    resources :users
    resources :hurdles
    resources :wattballs
    resources :teams
    resources :umpires
    resources :matches
    resources :tickets
    resources :scores
    resources :heats do
      member do
        get 'add_result'
        put 'update_result'
      end
    end
    resources :tournaments do
      member do
        post 'generate_heats'
        post 'populate_heats'
        post 'delete_heats'
        post 'set_results' #testing
      end
    end
    resources :sales, only: [:index]
    match "/tickets/:id/activate" => "tickets#activate", :as => "activate_ticket"
    match '/staffsignin', to: 'staff_sessions#new'
    match '/staffsignout', to: 'staff_sessions#destroy', via: :delete
    match '', to: 'dashboard#index'
    match 'admin/matches', to: "admin#matches"
    match 'admin/salesreport', to: "admin#help"
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def help
	end

	def about
	end

	def contact
	end

	def participants
	end

	def schedules
	end

	def staff
	end
	def direction
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
    <h1>About Us</h1>
    <p>
      The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      is a project to make a book and screencasts to teach web development
      with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
      is the sample application for the tutorial.
<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.uk/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=heriot+watt+university+edinburgh+sports+center&amp;aq=&amp;sll=57.746995,-4.687341&amp;sspn=6.101117,17.62207&amp;t=h&amp;ie=UTF8&amp;hq=heriot+watt+university+edinburgh+sports+center&amp;hnear=&amp;ll=55.908906,-3.318644&amp;spn=0.003127,0.008605&amp;z=14&amp;iwloc=A&amp;cid=8757079498320237953&amp;output=embed"></iframe><br /><small><a href="https://maps.google.co.uk/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=heriot+watt+university+edinburgh+sports+center&amp;aq=&amp;sll=57.746995,-4.687341&amp;sspn=6.101117,17.62207&amp;t=h&amp;ie=UTF8&amp;hq=heriot+watt+university+edinburgh+sports+center&amp;hnear=&amp;ll=55.908906,-3.318644&amp;spn=0.003127,0.008605&amp;z=14&amp;iwloc=A&amp;cid=8757079498320237953" style="color:#0000FF;text-align:left">View Larger Map</a></small>
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
    <h1>Contact</h1>
    <p>
     	contact page.
    </p>

app/views/static_pages/direction.html.erb
<% provide(:title, 'Directions') %>
    <h1>Directions</h1>
    <p>

<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.uk/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Heriot-Watt+University,+Edinburgh+EH14+4AS&amp;aq=&amp;sll=56.050567,-3.504639&amp;sspn=0.797614,2.202759&amp;t=h&amp;ie=UTF8&amp;hq=Heriot-Watt+University,+Edinburgh&amp;hnear=Currie+EH14+4AS,+United+Kingdom&amp;cid=8757079498320237953&amp;ll=55.910541,-3.317764&amp;spn=0.004209,0.00912&amp;z=16&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="https://maps.google.co.uk/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Heriot-Watt+University,+Edinburgh+EH14+4AS&amp;aq=&amp;sll=56.050567,-3.504639&amp;sspn=0.797614,2.202759&amp;t=h&amp;ie=UTF8&amp;hq=Heriot-Watt+University,+Edinburgh&amp;hnear=Currie+EH14+4AS,+United+Kingdom&amp;cid=8757079498320237953&amp;ll=55.910541,-3.317764&amp;spn=0.004209,0.00912&amp;z=16&amp;iwloc=A" style="color:#0000FF;text-align:right">View Larger Map</a></small>
    </p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
    <h1>Help</h1>
    <p>
	To get help contact an administrator or send email to <a href="mailto:kdnalus@gmail.com">kdnalus@gmail.com</a>
    </p>

app/views/static_pages/home.html.erb
<% provide(:title, '') %>
<div class="center hero-unit">
	<h1>Welcome to the Riccarton Sports Centre Tournament</h1>

	<h2>This is the home page for the Heriot-Watt Sports Tournament.</h2>
  <% if Tournament.exists?(1) and DateTime.now <= Tournament.find(1).end_date %>
    <% if DateTime.now >= Tournament.find(1).start_date %>
    <%else%>
      <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary pull-left" %>
    <%end%>
  	<%= link_to "Reserve Tickets",new_ticket_path,class: "btn btn-large btn-primary pull-right" %>
  <%end%>
	
</div>

<div class="tabbable tabs-left">
  <ul class="nav nav-tabs">
    <%= link_to "Schedules", '/schedules' %>
    <%= link_to "Participants", '/participants' %> 
  </ul>
  <div class="tab-content">
  </div>
</div>
<div>Powered by <a href="http://www2.macs.hw.ac.uk/~js249/">Victory Lies Ahead</a></div>

app/views/static_pages/participants.html.erb
<div class="center hero-unit">
	<h1>Participants</h1>
</div>

app/views/static_pages/schedules.html.erb
<div class="center hero-unit">
  <h1>Schedules</h1>
    <%#= link_to 'WattBall Fixtures', matches_path,  class: "btn btn-large btn-primary" %>
    <%= link_to 'Hurdle Heats', heats_path, class: "btn btn-large btn-primary" %>
  <h2>
    schedules for the tournament would be displayed here
  </h2>
</div>