config/routes.rb
SampleApp::Application.routes.draw do

  get "score/index"

  resources :users, :hurdles, :wattballs, :teams, :matches, :tickets, :scores, :heats
  match '/tickets/send_mail', to: 'tickets#send_mail'
  resources :sessions, only: [:new, :create, :destroy]
  

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/help',    to: "static_pages#help"
  match '/about',   to:"static_pages#about"
  match '/contact', to: "static_pages#contact"
  match '/direction', to: "static_pages#direction"
  
  match '/participants', to: "static_pages#participants"
  match '/participants/athletes', to: "hurdles#index"
  match '/participants/teams', to: "teams#index"
  
  match '/schedules', to: "static_pages#schedules"
  match '/schedules/matches', to: "matches#index"
  match '/schedules/heats', to: "heats#index"
  match '/topscorers', to: "scores#index"

  
  root to: 'static_pages#home'
  
  namespace :admin do
    resources :staffs
    resources :staff_sessions, only: [:new, :create, :destroy]
    resources :users
    resources :hurdles
    resources :wattballs
    resources :teams
    resources :umpires
    resources :matches
    resources :tickets
    resources :scores
    resources :heats do
      member do
        get 'add_result'
        put 'update_result'
      end
    end
    resources :tournaments do
      member do
        post 'generate_heats'
        post 'populate_heats'
        post 'delete_heats'
        post 'set_results' #testing
      end
    end
    resources :sales, only: [:index]
    match "/tickets/:id/activate" => "tickets#activate", :as => "activate_ticket"
    match '/staffsignin', to: 'staff_sessions#new'
    match '/staffsignout', to: 'staff_sessions#destroy', via: :delete
    match '', to: 'dashboard#index'
    match 'admin/matches', to: "admin#matches"
    match 'admin/salesreport', to: "admin#help"
  end

end

app/models/hurdle.rb
# == Schema Information
#
# Table name: hurdles
#
#  id            :integer          not null, primary key
#  first_name    :string(255)
#  last_name     :string(255)
#  qualification :time
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :integer
#  gender        :string(255)
#  round         :integer
#

class Hurdle < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :qualification, :gender, :user_id, :round

  belongs_to :user
  has_many :heats, through: :heat_hurdles
  has_many :heat_hurdles
  has_many :heat_results

  validates :user_id, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :gender, presence: true, length: {maximum: 1} 
  validates :qualification, presence: true

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/hurdles_controller.rb
class Admin::HurdlesController < Admin::AdminBaseController
  def new
 @hurdle = Hurdle.new
  end

  def show
    @hurdle = Hurdle.find(params[:id])
  end
  
  def index
    @hurdles = Hurdle.order(sort_column(Hurdle) + " " + sort_direction)
  end
    
  def create
    @hurdle = Hurdle.new(params[:hurdle])
    if @hurdle.save
      redirect_to admin_hurdles_url, notice: "Hurdle athlete is now registred!"
    else
      render 'new'
    end
  end
  
  def destroy
    @hurdle = Hurdle.find(params[:id])
    @hurdle.destroy
    redirect_to admin_hurdles_url, :notice => "Successfully deleted a hurdle racer"
  end

 def edit
    @hurdle = Hurdle.find(params[:id])
 end
 
 def update
   @hurdle = Hurdle.find(params[:id])
   params[:hurdle][:user_id] = (Hurdle.where(id: params[:id]).pluck(:user_id)).first
   if @hurdle.update_attributes(params[:hurdle])
     redirect_to [:admin,@hurdle], notice: "Successfully updated a Hurdle."
   else
     render action: 'edit'
    end
 end
end

app/controllers/hurdles_controller.rb
class HurdlesController < ApplicationController
    def new
	@hurdle = Hurdle.new
    end

    def show
        @hurdle = Hurdle.find(params[:id])
    end

    def index	
	@hurdles = Hurdle.order("round DESC, gender, qualification ASC")
    end
    
    def create
      @hurdle = current_user.hurdles.build(params[:hurdle])

      #if qualified skip round 0
      qual = @hurdle.qualification
      if qual.min == 0 && qual.hour == 0 && qual.sec == 0
        @hurdle.round = 0
      else
        @hurdle.round = 1
      end

      if @hurdle.save
        flash[:success] = "Hurdle athlete is now registred!"
        redirect_to @hurdle
      else
        render 'new'
      end
    end
  end

app/helpers/hurdles_helper.rb
module HurdlesHelper
end

app/views/admin/hurdles/_form.html.erb
<%= form_for ([:admin, @hurdle]) do |f| %>
  <%= render 'shared/error_messages', entity: @hurdle %> 
    <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>

    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
    
  <p> Qualification time must be given in the format HH:MM:SS </p>
    <%= f.label :qualification %><br />
    <%= f.text_field :qualification %>

    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
    
    <%= f.hidden_field :user_id, :value => params[:user_id] %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/admin/hurdles/edit.html.erb
<% provide(:title, "Edit Hurdle racer") %>

<%= render 'form' %>

<p>
  <%= link_to "Show", [:admin,@hurdle] %> |
  <%= link_to "View All", admin_hurdle_path %>
</p>

app/views/admin/hurdles/index.html.erb
<% provide(:title, "Hurldes") %>
<head>
  <h2> Hurdles </h2>
</head>
<body>
  <table class ="table table-striped" border = "3" cellpadding = "3" align = "center">
    <thead>
      <tr>
	<th><%= sortable "first_name", Hurdle, "First Name" %></th>
	<th><%= sortable "last_name", Hurdle, "Last Name" %></th>
	<th><%= sortable "qualification", Hurdle %></th>
	<th><%= sortable "gender", Hurdle %></th>
	<th colspan ="3"><%= sortable "id", Hurdle, "Options" %></th></th>
      </tr>
    </thead>
    <tbody>
      <% for hurdle in @hurdles %>
      <tr>
	<td><%= hurdle.first_name %></td>	
	<td><%= hurdle.last_name %></td>
	<td><%= hurdle.qualification %></td>
	<td><%= hurdle.gender %></td>
	<td><%= link_to "Show", [:admin,hurdle] %></td>
	<td><%= link_to "Edit", edit_admin_hurdle_path(hurdle) %></td>
	<td><%= link_to "Destroy", [:admin,hurdle], :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
</body>


<p><%= link_to "Back to Dashboard", admin_path %></p>

app/views/admin/hurdles/new.html.erb
<% provide(:title, "Edit Hurdle") %>
<%= render 'form' %>

<p><%= link_to "Back to List", admin_hurdles_path %></p>

app/views/admin/hurdles/show.html.erb
<% provide(:title, "New Hurdle") %>

  <strong>First Name:</strong>
  <%= @hurdle.first_name %> <br>

  <strong>Last Name:</strong>
  <%= @hurdle.last_name %> <br>
  
  <strong>Qualification:</strong>
  <%= @hurdle.qualification %> <br>

  <strong>Name:</strong>
  <%= @hurdle.gender %> <br>
</p>

<p>
  <%= link_to "Edit", edit_admin_hurdle_path(@hurdle) %> |
  <%= link_to "Destroy", admin_hurdle_path(@hurdle), :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", admin_hurdles_path %>
</p>