config/routes.rb
SampleApp::Application.routes.draw do

  get "score/index"

  resources :users, :hurdles, :wattballs, :teams, :matches, :tickets, :scores, :heats
  match '/tickets/send_mail', to: 'tickets#send_mail'
  resources :sessions, only: [:new, :create, :destroy]
  

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/help',    to: "static_pages#help"
  match '/about',   to:"static_pages#about"
  match '/contact', to: "static_pages#contact"
  match '/direction', to: "static_pages#direction"
  
  match '/participants', to: "static_pages#participants"
  match '/participants/athletes', to: "hurdles#index"
  match '/participants/teams', to: "teams#index"
  
  match '/schedules', to: "static_pages#schedules"
  match '/schedules/matches', to: "matches#index"
  match '/schedules/heats', to: "heats#index"
  match '/topscorers', to: "scores#index"

  
  root to: 'static_pages#home'
  
  namespace :admin do
    resources :staffs
    resources :staff_sessions, only: [:new, :create, :destroy]
    resources :users
    resources :hurdles
    resources :wattballs
    resources :teams
    resources :umpires
    resources :matches
    resources :tickets
    resources :scores
    resources :heats do
      member do
        get 'add_result'
        put 'update_result'
      end
    end
    resources :tournaments do
      member do
        post 'generate_heats'
        post 'populate_heats'
        post 'delete_heats'
        post 'set_results' #testing
      end
    end
    resources :sales, only: [:index]
    match "/tickets/:id/activate" => "tickets#activate", :as => "activate_ticket"
    match '/staffsignin', to: 'staff_sessions#new'
    match '/staffsignout', to: 'staff_sessions#destroy', via: :delete
    match '', to: 'dashboard#index'
    match 'admin/matches', to: "admin#matches"
    match 'admin/salesreport', to: "admin#help"
  end

end

app/models/match.rb
# == Schema Information
#
# Table name: matches
#
#  id         :integer          not null, primary key
#  when       :datetime
#  homeTeam   :string(255)
#  awayTeam   :string(255)
#  pitch      :integer
#  umpire     :string(255)
#  homeGoals  :integer
#  awayGoals  :integer
#  team_id_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  umpire_id  :integer
#  team_id    :integer
#

class Match < ActiveRecord::Base
  attr_accessible :awayGoals, :awayTeam, :homeGoals, :homeTeam, :pitch, :umpire, :when, :umpires_attributes, :teams_attributes , :tournament_id
  
  has_one :teams
  has_many :scores
  accepts_nested_attributes_for :teams
  
  has_one :umpires
  accepts_nested_attributes_for :umpires

  belongs_to :tournament
  
  validates :pitch, presence: true


  def teams
    [homeTeam,awayTeam]
    end

  def players
    cur_players = teams.map do |p|
     Wattball.where(["team_id = ?",p])
    end

    cur_players.flatten
  end
end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < Admin::AdminBaseController 
  def new
    @tournament = Tournament.find(1)
    @matches = Match.all
    @teams = Team.all
    @umpires = Umpire.all
    if not @matches.length == 0
      Match.delete_all
      redirect_to admin_matches_url, notice: "Schedule deleted"
    else
      matchDates = populateDays(@tournament).shuffle
      i = 1
      matchArray = Array.new()
      while i <= Team.maximum('id') do
        j = i + 1
        while j <= Team.maximum('id') do
          if Team.exists?(i) and Team.exists?(j)
            matchArray << [Team.find(i).id, Team.find(j).id]
          end
          j+= 1
        end
        i += 1
      end
      @matchArray = Array.new()
      matchArray = matchArray.shuffle
      matchArray.each do |match|
        matchDates = matchDates.shuffle
        dated = false
        matchDates.each do |date|
          if dated == false and validateAvaliable(match[0], match[1], @matchArray,date)
            date[1] += 1
            @matchArray<<(match << date[0]<< date[1])
            dated = true
          end
        end
      end

      if not @matchArray.length == matchArray.length
        redirect_to admin_matches_url, notice: "Not enough Timeslots/Pitches to schedule all games "  + 9785.chr(Encoding::UTF_8)
      else
        @matchUmpArray = Array.new()
        matchArray.each do |match|
          @umpires = @umpires.shuffle
          umped = false
          @umpires.each do |umpire|
            if umped == false and validateUmpAvail(umpire, match, @matchUmpArray)
              @matchUmpArray << (match << umpire.id)
              umped = true
            end
          end
        end
        if @matchArray.length == @matchUmpArray.length
          @matchArray = @matchUmpArray
          matchArray.each do |match|
            enterMatch = Match.create()
            enterMatch.homeTeam = match[0]
            enterMatch.awayTeam = match[1]
            enterMatch.when = match[2]
            enterMatch.pitch = match[3]
            enterMatch.umpire = match[4]
            enterMatch.save
          end
        redirect_to admin_matches_url, notice: "Successfully generated schedule!"
        else
          redirect_to admin_matches_url, notice: "Not enough Umpires to schedule all games "  + 9785.chr(Encoding::UTF_8)
        end
      end  
    end
  end

  def populateDays(tour)
    @tour = tour
    @first = tour.start_date
    #changed minute to min
    if @first.hour >= 11 and @first.min >= 1
      @start = DateTime.new(@first.year,@first.month,@first.day,15,00,00,'')
    else
      @start = DateTime.new(@first.year,@first.month,@first.day,11,00,00,'')
    end
    i = 0
    dateArray = Array.new()
    lastDate = @start
    dateArray << [@start, 0]

    while lastDate < tour.end_date do
      if lastDate.hour == 11 and (lastDate + 4.hour)< tour.end_date
        lastDate = lastDate + 4.hour
        dateArray << [lastDate, 0]
      elsif lastDate.hour == 15 and (lastDate + 20.hour)< tour.end_date
        lastDate = lastDate + 20.hour
        dateArray << [lastDate, 0]
      else (lastDate.hour == 15 and (lastDate + 20.hour)>= tour.end_date) or (lastDate.hour == 11 and (lastDate + 4.hour)>= tour.end_date)
        lastDate = tour.end_date
      end
      i += 1
    end
    return dateArray
  end

#########################
  def validateAvaliable(p1, p2, m, d)
    free = true
    playing1 = p1
    playing2 = p2
    matches = m
    date = d
    matches.each do |match|
      if match[2]==date[0] and ((playing1 == match[0] or playing1 == match[1]) or (playing2 == match[0] or playing2 == match[1]))
        free = false
      end
    end
    return free
  end
#########################
  def validateUmpAvail(u, ma, mu)
    umpire = u
    match = ma
    matches = mu
    free = true
    matches.each do |current|
      if current[2] == match[2] and current[4] == umpire.id
        free = false
      end
    end
    return free
  end
#########################

  def show
    @match = Match.find(params[:id])
  end
  
  def index
    if Match.count > 0
      @matches = Match.order("`when` ASC")
    else
      @matches = Match.all
    end
  end
    
  def create
    @match = Match.new(params[:match])
    if @match.save
      redirect_to admin_matches_url, notice: "Match is now created!"
    else
      render 'new'
    end
  end
  
  def destroy
    @match = Match.find(params[:id])
    @match.destroy
    redirect_to admin_matches_url, :notice => "Successfully deleted match!"
  end

 def edit
   @match = Match.find(params[:id])
 end
 
 def update
    @match = Match.find(params[:id])
    if @match.update_attributes(params[:match])
      flash[:success] = "Match result updated"
      redirect_to  [:admin,@match]
    else
      render 'edit'
    end
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  include ActiveModel::MassAssignmentSecurity

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
    @teams = Team.all(:select => "team_name")
	end

  
  def show
    @match = Match.find(params[:id])
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/admin/matches/_form.html.erb
<%= form_for([:admin,@match]) do |f| %>
  <%= render 'shared/error_messages', entity: @match %> 

<div id = "container" >
  <div id="v-div" style = "height:100%;width:50%;float:left;" >
    <h2><%= Team.find(@match.homeTeam).team_name %> <%= @match.homeGoals %> </h2>
       <div class="field">
	 <%= f.label :homeGoals %><br />
	 <%= f.number_field :homeGoals,value: 0, min: 0, max: 10%>
       </div>

  </div >

  <div id="v-div2" style = "height:100%;width:50%;float:right;" >
    <h2> <%= Team.find(@match.awayTeam).team_name %> <%= @match.awayGoals %> </h2>
       <div class="field">
	 <%= f.label :awayGoals %><br />
	 <%= f.number_field :awayGoals,value: 0, min: 0, max: 10%>
       </div>
  </div >
</div>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/admin/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin,@match] %> |
<%= link_to 'Back', admin_matches_path %>

app/views/admin/matches/index.html.erb
<h1>Listing matches</h1>
<% if Match.count > 0 %>
    <table class ="table table-striped" border = "3" cellpadding = "3" align = "center">
        <tr bgcolor="grey">
    	<th><%= sortable "when", Match, "Date" %></th>
    	<th><%= sortable "id", Match, "Time" %></th>
    	<th><%= sortable "ptich", Match, "Pitch" %></th>
    	<th><%= sortable "umpire", Match, "Umpire" %></th>
    	<th><%= sortable "homeTeam", Match, "Home Team" %></th>
    	<th><%= sortable "id", Match, "Score" %></th>
    	<th><%= sortable "awayTeam", Match, "Away Team" %></th>
    	<th colspan ="3"><%= sortable "id",Match, "Options" %></th>
        </tr>
        <% @matches.each do |match| %>
            <tr>
                <td><%= match.when.strftime('%e %b %Y') %></td>
                <td><%= match.when.strftime('%H:%M:%S') %></td>
                <td><%= match.pitch %></td>
                <td><%= Umpire.find(match.umpire).first_name + " " + Umpire.find(match.umpire).last_name %></td>
                <td><%= Team.find(match.homeTeam).team_name %></td>
                <% if match.homeGoals == nil or match.awayGoals == nil %>
                    <td><%=  %></td>
                <% else %>
                    <td><%= match.homeGoals.to_s + " - " + match.awayGoals.to_s %></td>
                <% end %>
                <td><%= Team.find(match.awayTeam).team_name %></td>
                <td><%= link_to 'Show', [:admin,match] %></td>
                <td><%= link_to 'Edit', edit_admin_match_path(match) %></td>
    	    <% if is_admin? %>
                <td><%= link_to 'Destroy', [:admin,match], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    	    <% end %>
            </tr>
        <% end %>
    </table>
<% end%>

<% if not Tournament.exists?(1) %>
    <h2> Tournament has not been created </h2>
<% elsif not Team.count > 1 %>
    <h2> 2 or more teams must be registered to generate a schedule </h2>
<% elsif Match.count == 0 %>
    <%= link_to 'Generate New Schedule', new_admin_match_path, class: "btn btn-large btn-primary" %>
<% elsif not Match.count == 0 %>
    <%= link_to 'Delete Schedule', new_admin_match_path, class: "btn btn-large btn-primary" %>
<% end %>

app/views/admin/matches/new.html.erb
<h1>New match</h1>

<br>
<% @matchArray.each do |match| %>
	<%= match %>
	<br>
<%end %>
<br>

<%= link_to 'Back', admin_matches_path %>

app/views/admin/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Kick Off:</b>
  <%= @match.when %>
</p>

<p>
  <b>Home Team:</b>
  <%= @match.homeTeam %>
</p>

<p>
  <b>Away Team:</b>
  <%= @match.awayTeam %>
</p>

<p>
  <b>Pitch:</b>
  <%= @match.pitch %>
</p>

<p>
  <b>Umpire:</b>
  <%= @match.umpire %>
</p>
<% if @match.homeGoals == nil or @match.awayGoals == nil %>
  Match has not been played!
<% else %>
<p>
  <b>Home Goals:</b>
  <%= @match.homeGoals %>
</p>

<p>
  <b>Away Goals:</b>
  <%= @match.awayGoals %>
</p>
<% end %>

<%= link_to 'Edit', edit_admin_match_path(@match) %> |
<%= link_to 'Back', admin_matches_path %>