config/routes.rb
SampleApp::Application.routes.draw do

  get "score/index"

  resources :users, :hurdles, :wattballs, :teams, :matches, :tickets, :scores, :heats
  match '/tickets/send_mail', to: 'tickets#send_mail'
  resources :sessions, only: [:new, :create, :destroy]
  

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/help',    to: "static_pages#help"
  match '/about',   to:"static_pages#about"
  match '/contact', to: "static_pages#contact"
  match '/direction', to: "static_pages#direction"
  
  match '/participants', to: "static_pages#participants"
  match '/participants/athletes', to: "hurdles#index"
  match '/participants/teams', to: "teams#index"
  
  match '/schedules', to: "static_pages#schedules"
  match '/schedules/matches', to: "matches#index"
  match '/schedules/heats', to: "heats#index"
  match '/topscorers', to: "scores#index"

  
  root to: 'static_pages#home'
  
  namespace :admin do
    resources :staffs
    resources :staff_sessions, only: [:new, :create, :destroy]
    resources :users
    resources :hurdles
    resources :wattballs
    resources :teams
    resources :umpires
    resources :matches
    resources :tickets
    resources :scores
    resources :heats do
      member do
        get 'add_result'
        put 'update_result'
      end
    end
    resources :tournaments do
      member do
        post 'generate_heats'
        post 'populate_heats'
        post 'delete_heats'
        post 'set_results' #testing
      end
    end
    resources :sales, only: [:index]
    match "/tickets/:id/activate" => "tickets#activate", :as => "activate_ticket"
    match '/staffsignin', to: 'staff_sessions#new'
    match '/staffsignout', to: 'staff_sessions#destroy', via: :delete
    match '', to: 'dashboard#index'
    match 'admin/matches', to: "admin#matches"
    match 'admin/salesreport', to: "admin#help"
  end

end

app/models/umpire.rb
# == Schema Information
#
# Table name: umpires
#
#  id         :integer          not null, primary key
#  first_name :string(255)
#  last_name  :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  umpire_id  :integer
#  match_id   :integer
#

class Umpire < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name
  
  belongs_to :matches
  validates_uniqueness_of :first_name, :scope => :last_name
end

app/controllers/admin/umpires_controller.rb
class Admin::UmpiresController < Admin::AdminBaseController
  def new
    @umpire = Umpire.new	
  end

  def show
    @umpire = Umpire.find(params[:id])
  end

  def index
    @umpires = Umpire.order(sort_column(Umpire) + " " + sort_direction)
  end

  def edit
    @umpire = Umpire.find(params[:id])
  end

  def update
    @umpire = Umpire.find(params[:id])
    if @umpire.update_attributes(params[:umpire])
      redirect_to [:admin,@umpire], :notice  => "Successfully updated umpire details"
    else
      render :action => 'edit'
    end
  end 

  def create	
  @umpire = Umpire.new(params[:umpire])
    if @umpire.save
      redirect_to [:admin,@umpire], notice: "Umpire is now registred!"
    else
      render 'new'
    end
  end
end

app/helpers/umpires_helper.rb
module UmpiresHelper
end

app/views/admin/umpires/_form.html.erb
<%= form_for([:admin,@umpire]) do |f| %>
<%= render 'shared/error_messages', entity: @umpire %>
 

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/umpires/edit.html.erb
<h1>Editing umpire</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin,@umpire] %> |
<%= link_to 'Back', admin_umpires_path %>

app/views/admin/umpires/index.html.erb
<% provide(:title, "Umpires") %>
<head>
  <h2> Umpires </h2>
</head>
<body>
<table class ="table table-striped" border = "3" cellpadding = "3" align = "center">
  		<thead>
		  <tr>
			  <th><%= sortable "first_name", Umpire, "First Name" %></th>
			  <th><%= sortable "last_name", Umpire, "Last Name" %></th>
			  <th><%= sortable "email", Umpire, "Email Address" %></th>
			  <th colspan ="3"><%= sortable "id", Umpire, "Options" %></th></th>
			</tr>
      	</thead>
		<tbody>
			<% for umpire in @umpires %>
			<tr>
			  <td><%= umpire.first_name %></td>
			  <td><%= umpire.last_name %></td>
			  <td><%= umpire.email %></td>
			  <td><%= link_to "Show", [:admin,umpire]%></td>
			  <td><%= link_to "Edit", edit_admin_umpire_path(umpire) %></td>
			  <td><%= link_to "Delete", [:admin,umpire], :confirm => 'Are you sure?', :method => :delete %></td>
			</tr>
      	</tbody>
      		<% end %>
    </table>
  </section>
</body>
<p><%= link_to "New umpire", new_admin_umpire_path %></p>
<p><%= link_to "Back to Dashboard", admin_path %></p>

app/views/admin/umpires/new.html.erb
<h1>New umpire</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_umpires_path %>

app/views/admin/umpires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @umpire.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @umpire.last_name %>
</p>
<h3> <%= @umpire.first_name %>  <%= @umpire.last_name %> Schedule </h3>
<table class ="table table-striped" border = "3" cellpadding = "3" align = "center">
  <thead>
    <tr>
      <th><%= sortable "when", Umpire, "Date of match" %></th>
      <th><%= sortable "id", Umpire, "Home Team" %></th>
      <th><%= sortable "id", Umpire, "Away Team" %></th>
    </tr>
  </thead>
  <tbody>
    <% match = Match.where(["umpire = ?",@umpire.id]) %>
    <% for m_info in match %>
    <tr>
      <td><%= m_info.when.strftime('%e %b %Y - %H:%M:%S')%></td>
      <td><%= Team.find(m_info.homeTeam).team_name %></td>
      <td><%= Team.find(m_info.awayTeam).team_name %></td>
    </tr>
  </tbody>
  <% end %>
</table>

<%= link_to 'Edit', edit_admin_umpire_path(@umpire) %> |
<%= link_to 'Back', admin_umpires_path %>